#!/usr/bin/env bash
#
# Use https://git.io/vPBwZ to download the latest version of it
#

exeOnInstall() {
  arch-chroot /mnt $@
}

echo "This will install linux arch with following settings:"
echo "* Install it in UEFI mode"
echo "* partitions with LVM"
echo "  1. partition: UEFI (512 MB)"
echo "  2. partition: SWAP (1.25 times your RAM)"
echo "  3. partition: ROOT (user-defined)"
echo "  4. partition: HOME (user-defined)"
echo "* German keyboard and locale"

read -p "Are you sure you want that?[yn] " -r
echo    # move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
  exit 1
fi

if [ ! -d "/sys/firmware/efi" ]; then
  echo "Not booted in UEFI mode! Please reboot with UEFI enabled."
  exit 1
else
  echo "UEFI mode enabled"
fi

ping -q -c2 archlinux.org > /dev/null
if [ $? -eq 0 ]
then
	echo "Internet available"
else
  echo "No internet available, please check the connectivity and try again!"
  exit 1
fi

read -p "Is a proxy setup needed?[yn] " -r
echo    # move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  read -p "Enter the address of the proxy:" -r
  echo    # move to a new line
  export http_proxy=$REPLY
  export https_proxy=$REPLY
fi

read -p "Please specify the device to format and install arch on:[/dev/sda] " -r
echo    # move to a new line
installDev="/dev/sda"
if [ ! -z $REPLY ];
then
  installDev=$REPLY
fi

echo "Set german keyboard..."
loadkeys de-latin1

echo "Partition harddisk..."
ramSize=`sed -n -e '/^MemTotal/s/^[^0-9]*//p' /proc/meminfo | grep -o --regexp "[0-9]*"`
swapSize=`expr $ramSize / 4`
swapSize=`expr $ramSize + $swapSize`
swapSize=`expr $swapSize / 1024`
swapSize+="M"
echo "Estimated SWAP size: $swapSize"

sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | gdisk $installDev
  n # new
  1 # first partition
    # default start sector
  +512M # 512 MB UEFI partition
  EF00 # UEFI type
  n # new
  2 # first partition
    # default start sector
  +$swapSize # SWAP size
  8200 # SWAP type
  n # new
  3 # first partition
    # default start sector
    # default end sector (all free space)
  8300 # linux filesystem
  p # print the in-memory partition table
  w # write the partition table
  y # accept changes
EOF

read -p "How big should the root partition be:[10G] " -r
echo    # move to a new line
rootPartSize="10G"
if [ ! -z $REPLY ];
then
  rootPartSize=$REPLY
fi

pvcreate ${installDev}3
vgcreate lvm ${installDev}3
lvcreate --name root -L${rootPartSize} lvm # root partition
lvcreate --name home -l100%FREE lvm  # home partition
lvscan

echo "Format partitions..."

mkfs.fat -F 32 ${installDev}1
mkswap -L swap ${installDev}2
mkfs.ext4 -L root /dev/lvm/root
mkfs.ext4 -L home /dev/lvm/home

echo "Mount partitions..."

mount /dev/lvm/root /mnt # root
mkdir -p /mnt/home
mount /dev/lvm/home /mnt/home # home
mkdir -p /mnt/boot
mount ${installDev}1 /mnt/boot # EFI

swapon -L swap

echo "Install Arch linux to disk..."
mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
wget -O /etc/pacman.d/mirrorlist "https://www.archlinux.org/mirrorlist/?country=DE&protocol=https&ip_version=4&ip_version=6&use_mirror_status=on"
sed -i "/^#Server/s/^#//" /etc/pacman.d/mirrorlist

pacstrap /mnt base base-devel

echo "Generate fstab..."
genfstab -Lp /mnt > /mnt/etc/fstab
cat /mnt/etc/fstab

echo "Config system..."

read -p "Hostname: [arch]" -r
echo    # move to a new line
hostname="arch"
if [ ! -z $REPLY ];
then
  hostname=$REPLY
fi

exeOnInstall echo $hostname > /etc/hostname

exeOnInstall echo LANG=de_DE.UTF-8 > /etc/locale.conf
exeOnInstall echo LC_COLLATE=C >> /etc/locale.conf
exeOnInstall echo LANGUAGE=de_DE >> /etc/locale.conf

exeOnInstall ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime

exeOnInstall cp /etc/locale.gen /etc/locale.gen.bak
exeOnInstall sed -i "/^#de_DE.UTF-8/s/^#//" /etc/locale.gen
exeOnInstall sed -i "/^#de_DE\wISO-8859-1/s/^#//" /etc/locale.gen
exeOnInstall sed -i "/^#en_US.UTF-8/s/^#//" /etc/locale.gen
exeOnInstall locale-gen

cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist

exeOnInstall pacman -Sy

#make the group wheel ready to use with sudo
exeOnInstall sed -i "/%wheel\wALL=(ALL)\wALL/s/^#//" /etc/sudoers
#make a proxy available for sudo
exeOnInstall echo "Defaults env_keep += \"http_proxy\"" >> /etc/sudoers
exeOnInstall echo "Defaults env_keep += \"https_proxy\"" >> /etc/sudoers

echo "Install kernel..."

exeOnInstall mkinitcpio -p linux

echo "Set root password..."

read -s -p "Root password:[arch] " -r
echo    # move to a new line
rootPass="arch"
if [ ! -z $REPLY ];
then
  rootPass=$REPLY
fi

exeOnInstall sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | passwd
  $rootPass # password
  $rootPass # second time
EOF

echo "Install GRUB..."
exeOnInstall echo 'y' | pacman -Sq grub efibootmgr

exeOnInstall grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub
exeOnInstall grub-mkconfig -o /boot/grub/grub.cfg

echo "Exit installed system. Please reboot now to switch to your fresh arch linux."
